baseurl: ''
description: Just another PHP developer
email: minottoemanuele@gmail.com
github_username: EmanueleMinotto
linkedin_username: EmanueleMinotto
markdown: kramdown
title: "Emanuele Minotto\u2019s Blog"
twitter_username: EmanueleMinotto
url: http://emanueleminotto.github.io
permalink: /blog/:title
